name: Norminette Check

on:
  pull_request:
    branches:
      - main
      - dev
	  - feature/*'
  push:
    branches:
      - main
      - dev
	  - feature/*'

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Norminette via pip
        run: |
          echo "Installation de Norminette avec pip..."
          python -m pip install --upgrade pip
          pip install norminette

      - name: Run Norminette
        run: |
          # Remplacer "src/" par le répertoire contenant ton code
          norminette src/  # Vérifier la norme pour le répertoire `src/`

