name: Norminette Check

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Norminette
        run: |
          echo "Vérification et installation de Norminette..."

          # Télécharger et installer Norminette à partir de GitHub
          curl -sSL https://github.com/42School/norminette/releases/download/v3.2.0/norminette-linux-x86_64 -o norminette
          chmod +x norminette
          mv norminette /usr/local/bin/

          # Vérifier si Norminette est bien installée
          norminette --version

      - name: Run Norminette
        run: |
          # Remplacer "src/" par le répertoire contenant ton code
          norminette src/  # Vérifier la norme pour le répertoire `src/`

