name: Norminette Check

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check if Norminette is installed
        run: |
          if ! command -v norminette &> /dev/null
          then
              echo "Norminette non trouvée, installation..."
              curl -sSL https://github.com/42School/norminette/releases/download/v3.2.0/norminette-linux-x86_64 -o norminette
              chmod +x norminette
              mv norminette /usr/local/bin/
          else
              echo "Norminette déjà installée"
          fi

      - name: Run Norminette
        run: |
          norminette  # Remplacer "norminette" par "norminette <chemin-ou-tester> ex: src/" par le répertoire contenant ton code

